In [17]:
import torch
import numpy as np 
import pandas as pd 
from time import time 
import torch.nn as nn 


In [ ]:
class LNN_Regression:

    def __init__(self,X,y,epochs,lr,reg_constant = None,reg_type = None):
        self.X = torch.tensor(X,dtype=torch.float32)
        self.y = torch.tensor(y,dtype=torch.float32).reshape(-1,1)
        self.linear = nn.Linear(X.shape[1],1)
        self.epochs = epochs
        self.lr = lr 
        self.reg_constant = reg_constant
        self.reg_type = reg_type 
        self.optimizer = torch.optim.SGD(
            self.linear.parameters(),
            lr = self.lr 
        )

    def forward(self,X):
        return self.linear(X)

    def fit(self):
        for _ in range(self.epochs):
            y_pred = self.forward(self.X)
            loss = self.loss(self.y,y_pred)
            # print(f"Loss @ Epoch {_} : ",loss)
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
            
    def loss(self,y,y_pred):
        fn = nn.MSELoss()
        penalty = 0

        if self.reg_type == "l1":

            penalty = (
                self.reg_constant
                * torch.sum(
                    torch.abs(self.linear.weight)
                )
            )

        elif self.reg_type == "l2":

            penalty = (
                self.reg_constant
                * 0.5
                * torch.sum(
                    self.linear.weight ** 2
                )
            )
        return fn(y,y_pred) + penalty

### Linear  Regressino without Regularization (Pytorch)

In [30]:

start = time()
X = np.arange(1, 11).reshape(-1, 1)
y = np.array([3, 4, 6, 7, 13, 18, 20, 23, 21, 25])

model = LNN_Regression(X, y, epochs=50000, lr=0.001)
model.fit()

end = time()

print("Total time : ", end-start)
# print("Weights:", model.W)
print("Weight:", model.linear.weight)
print("Bias:", model.linear.bias)
# print("Bias:", model.b)
# print("Predictions:", model.forward())

Total time :  16.96325421333313
Weight: Parameter containing:
tensor([[2.7030]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.8666], requires_grad=True)


### Linear  Regressino with L1 Regualarization (Pytorch)

In [31]:

start = time()
X = np.arange(1, 11).reshape(-1, 1)
y = np.array([3, 4, 6, 7, 13, 18, 20, 23, 21, 25])

model = LNN_Regression(X, y, epochs=50000, lr=0.001,reg_constant=0.01,reg_type="l1")
model.fit()

end = time()

print("Total time : ", end-start)
print("Weight:", model.linear.weight)
print("Bias:", model.linear.bias)
# print("Predictions:", model.forward())

Total time :  21.040305137634277
Weight: Parameter containing:
tensor([[2.7024]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.8632], requires_grad=True)


### Linear  Regressino with L2 Regualarization (Pytorch)

In [32]:

start = time()
X = np.arange(1, 11).reshape(-1, 1)
y = np.array([3, 4, 6, 7, 13, 18, 20, 23, 21, 25])

model = LNN_Regression(X, y, epochs=50000, lr=0.001,reg_constant=0.01,reg_type="l2")
model.fit()

end = time()

print("Total time : ", end-start)
print("Weight:", model.linear.weight)
print("Bias:", model.linear.bias)
# print("Predictions:", model.forward())

Total time :  22.213587284088135
Weight: Parameter containing:
tensor([[2.7014]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.8576], requires_grad=True)
